FROM ubuntu:20.04 AS builder
WORKDIR /project
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
    apt-get -qq install -y cmake git vim gcc g++ gfortran software-properties-common \
            python3-pip python3-matplotlib python3-numpy likwid

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 30 \
                        --slave   /usr/bin/pip    pip    /usr/bin/pip3

# Installing latest GCC compiler (version 10)
RUN apt-get -qq install -y gcc-10 g++-10 gfortran-10

# We are installing both OpenMPI and MPICH. We could use the update alternatives to switch between them
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 80 \
                        --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
                        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-9 \
                        --slave /usr/bin/gcov gcov /usr/bin/gcov-9

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90 \
                        --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
                        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 \
                        --slave /usr/bin/gcov gcov /usr/bin/gcov-10

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

RUN groupadd chapter4 && useradd -m -s /bin/bash -g chapter4 chapter4

WORKDIR /home/chapter4
RUN chown -R chapter4:chapter4 /home/chapter4
USER chapter4
ENV PATH=${PATH}:/opt/intel/oneapi/advisor/2021.1-beta08/bin64
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/intel/oneapi/compiler/2021.1-beta08/linux/compiler/lib/intel64_lin
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/intel/oneapi/compiler/2021.1-beta08/linux/lib

RUN git clone --recursive https://github.com/essentialsofparallelcomputing/Chapter4.git

WORKDIR /home/chapter4/Chapter4
#RUN make CC=gcc

ENTRYPOINT ["bash"]
